### ISSUE TITLE
2020-07-03-bear-package-1-dot-10.markdown で分からなかった点

### ISSUE THREAD

**Issue by kumamidori** [koriym/koriym.github.io#4]
https://github.com/koriym/koriym.github.io/blob/source/source/_posts/2020-07-03-bear-package-1-dot-10.markdown

> 複数コンテキストのコンパイルを行うときにはファイルの対比が必要です。

すみません、単に私が何か知らないだけのような気がするものの、この文の意味が私には取れませんでした。

**Comment by koriym** [comment]
コンテントネゴシエーションを行う場合など(ex. api-app, html-app)1つのアプリケーションで複数コンテキストのコンパイルを行うときにはファイルの退避が必要です。

```
mv autoload.php api.autoload.php
```

これでどうでしょうか？

**Comment by kumamidori** [comment]
なるほどそういう意味だったのですね。理解できました。ありがとうございます。

**Comment by koriym** [comment]
じゃあこれに直したらOKでしょうか？

**Comment by koriym** [comment]
> ファイルの対比が必要です。

これじゃ分からないですね。すいません！！^^;

**Comment by kumamidori** [comment]
教えて頂いてよく分かりましたので、こちらクローズして頂いてかまいません。ありがとうございました。
